##########################################################################
# (c) T-Systems International GmbH
# Auhtor: Andres Wendt (andres-martin.wendt@t-systems.com)
# Purpose:
# This will be used to hardened version of docker on given system.
# by using ansible. Harding will be based on CIS controls. Ansible code is
# inspired from https://github.com/mitre/ansible-cis-docker-ce-hardening
#
##########################################################################
# Input Parameter:
#
# Ouput Parameter
#
#
# additional files:
#
# needed providers
#
# Function:
#
##########################################################################
# Addtional information and references:
#   https://www.cisecurity.org/benchmark/docker/
##########################################################################
- name: 6.1 Ensure that image sprawl is avoided (Not Scored)
  command: "docker system prune -a -f"
  tags:
   - not_scored
   - section6.1
