##########################################################################
# (c) T-Systems International GmbH
# Auhtor: Andres Wendt (andres-martin.wendt@t-systems.com)
# Purpose:
# This will be used to hardened version of docker on given system.
# by using ansible. Harding will be based on CIS controls. Ansible code is
# inspired from https://github.com/mitre/ansible-cis-docker-ce-hardening
#
##########################################################################
# Input Parameter:
#
# Ouput Parameter
#
#
# additional files:
#
# needed providers
#
# Function:
#
##########################################################################
# Addtional information and references:
#   https://www.cisecurity.org/benchmark/docker/
##########################################################################

- name: 1.1.2 Ensure Docker is up to date (Not Scored)
  yum:
    name: docker-ce
    state: latest
  tags:
   - not_scored
   - section1.3


- name: 1.2.1 Ensure a separate partition for containers has been created (Scored)\
  debug: msg="This is a manual configuration"
  tags:
   - not_scored
   - section1.2

- name: 1.2.2 Ensure only trusted users are allowed to control Docker damein
  debug: msg="This is a manal configuration"
  tags:
   - scored
   - section1.2


- name: 1.2.3 Ensure auditing is configured for the docker daemon (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/bin/dockerd -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.2

- name: 1.2.4 Ensure auditing is configured for Docker files and directories - /var/lib/docker (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /var/lib/docker -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.2


- name: 1.2.5 Ensure auditing is configured for Docker files and directories - /etc/docker (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /etc/docker -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.2

- name: 1.2.6 Ensure auditing is configured for Docker files and directories - docker.service (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/lib/systemd/system/docker.service -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.2

- name: 1.2.7 Ensure auditing is configured for Docker files and directories - docker.socket (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/lib/systemd/system/docker.socket -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.2

- name: 1.2.8 Ensure auditing is configured for Docker files and directories - /etc/default/docker (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /etc/default/docker -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.2

- name: 1.2.9 Ensure auditing is configured for Docker files and directories - /etc/sysconfig/docker (scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /etc/sysconfig/docker -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.10


- name: 1.2.10 Ensure auditing is configured for Docker files and directories - /etc/docker/daemon.json (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /etc/docker/daemon.json -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.2

- name: 1.2.11 Ensure auditing is configured for Docker files and directories - /usr/bin/containerd (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/bin/containerd -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.2

- name: 1.2.12 Ensure auditing is configured for Docker files and directories - /bin/runc (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /bin/runc -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.2