##########################################################################
# (c) T-Systems International GmbH
# Auhtor: Andres Wendt (andres-martin.wendt@t-systems.com)
# Purpose:
# This will be used to install a hardened version of docker on given system.
# by using ansible. Harding will be based on CIS controls. Ansible code is
# inspired from https://github.com/mitre/ansible-cis-docker-ce-hardening
#
##########################################################################
# Input Parameter:
# all innput parameters will be set via environment varaiables
#
# Ouput Parameter
#
#
# additional files:
#
# needed providers
#
# Function:
#  - install firewalld
#  - configure firewall for master and etcd nodes
#  - restart firewall
#
##########################################################################
# Addtional information and references:
#   https://docs.docker.com/v17.09/engine/installation/linux/docker-ce/centos/
#   https://www.cisecurity.org/benchmark/docker/
##########################################################################
- hosts: "localhost"
  tasks:
  - name: Install firewalld
    package: name={{ item }} state=latest
    with_items:
    - firewalld
    - ipset

  - name: start firewalld
    service: name=firewalld state=started enabled=yes

  - name: configure firewall worker nodes
    command: firewall-cmd --permanent --add-port={{ item }}
    with_items:
      - 22/tcp
      - 80/tcp
      - 443/tcp
      - 2376/tcp
      - 8472/udp
      - 9099/tcp
      - 10250/tcp
      - 10254/tcp
      - 30000-32767/tcp
      - 30000-32767/udp

  - name: configure firwall open etcd ports
    command: firewall-cmd --permanent --add-port={{ item }}
    with_items:
      - 2376/tcp
      - 2379/tcp
      - 2380/tcp
      - 8472/udp
      - 9099/tcp
      - 10250/tcp

  - name: configure firewall open controlplane nodes
    command: firewall-cmd --permanent --add-port={{ item }}
    with_items:
      - 80/tcp
      - 443/tcp
      - 2376/tcp
      - 6443/tcp
      - 8472/udp
      - 9099/tcp
      - 10250/tcp
      - 10254/tcp
      - 30000-32767/tcp
      - 30000-32767/udp

  - name: Bounce firewalld
    service: name=firewalld state=restarted

